---
title: "Figures Ocean Solutions manuscript"
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
  code_folding: hide
fig_caption: yes
toc: yes
toc_float: yes
pdf_document:
  toc: yes
---
  
  
```{r prep, echo=FALSE, message= FALSE}
rm(list = ls())
library(tidyverse)
library(readxl)
library(knitr)       # kable : prettier data.frame output
library(viridis)
library(gridExtra)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
cols <- c("0" = "white", "1" = "blue", "2" = "blue", "3" = "blue3", "4" = "yellow", "5" = "blue4")
size_labs <- 6
face_font <- "plain"

Mytheme <- function(size_labs = 6, face_font="plain", ...) {
  theme_bw() +
  theme(axis.text.x = element_text(face=face_font, size=size_labs, color="black"),
        axis.title.x = element_text(face=face_font, size=size_labs, margin=margin(0,0,0,0,"pt")),
        axis.text.y = element_text(face=face_font, color="black", size=size_labs),
        axis.title.y = element_text(face=face_font, size=size_labs),
        axis.ticks.x = element_line(size=0.1),
        axis.ticks.y = element_line(size=0.1),
        axis.ticks.length = unit(1.1, "mm"),
        panel.grid.major = element_line(size = 0.25, color="black", linetype="dotted"),
        aspect.ratio = 1 / 1,
        plot.margin = margin(t = 0, r = 1, b = 0, l = 0, unit = "lines")
  )
}

file_name <- "../../../interim_documents/backups_google_docs/Ocean Solutions Tables_2017-05-17a.xlsx"
```

```{r Table 1a, warning=FALSE, echo=FALSE, message= FALSE}
dat <- read_xlsx(path = file_name,
                  skip=7, n_max = 10, trim_ws = TRUE,
                  sheet = "T1a solutions (global)", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::rename(Others = `Other Methods (CO2 extraction and storage, other GHG, hybrid)`) %>%
  dplyr::filter(
    grepl("uptake|warming|acidification|sea level|readiness|Affordability|Governability", Criteria)) %>%
  mutate_each(funs(substr(., 1, 1)), 2:8) %>%
  mutate_each(funs(as.integer), 2:8)

dat$Criteria[dat$Criteria == "Effectiveness to increase net carbon uptake"] <-  "Increase carbon uptake"
dat$Criteria[dat$Criteria == "Effectiveness to moderate warming"] <-  "Moderate warming"
dat$Criteria[dat$Criteria == "Effectiveness to moderate acidification (upper ocean/global)"] <-  "Moderate acidification"
dat$Criteria[dat$Criteria == "Effectiveness to moderate sea level rise"] <-  "Moderate sea level rise"
dat$Criteria[dat$Criteria == "Time commitment"] <-  "Time\ncommitment"
dat$Criteria[dat$Criteria == "Technological readiness"] <-  "Readiness"
dat$Criteria[dat$Criteria == "Lead time until effective"] <-  "Lead\ntime"
colnames(dat) <- c("Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)", "Others", "Cloud", "Albedo")
# long form
dat_long <- gather(data = dat, key = Solution, value = score, 2:8) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))
levels(dat_long$Criteria) <- rev(levels(dat_long$Criteria))

# Plot t1a #####
fig_t1a <- ggplot(data = dat_long, 
                 aes(x=Solution, 
                     y=Criteria, fill=score)) +
  labs(x = NULL, y = NULL, title = NULL) +
  geom_tile(color="black", size=0.1) +
  # scale_fill_manual(values = cols,
  #                   na.value = "gray90",
  #                   name = NULL,
  #                   guide = "legend",
  #                   labels = c("Nil", "Very low", "Low", "Moderate",
  #                                  "High", "Very high")) +
  scale_fill_gradient(name = NULL,
                      low = "white", high = "dodgerblue3",
                      space = "Lab", na.value = "gray90", guide = "legend",
                      labels = c("Nil", "Very low", "Low", "Moderate",
                                   "High", "Very high")) +
  coord_equal() +
  guides(fill = guide_legend(reverse = TRUE)) +
  scale_x_discrete(position = "top") +
  Mytheme(size_labs = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0, vjust = 0.5))
fig_t1a
ggsave(filename = "../figs/fig_t1a.png", plot = fig_t1a, width = 5, height = 5, units = "cm")
```

```{r Table 1b, warning=FALSE, echo=FALSE, message= FALSE}
dat <- read_xlsx(path = file_name,
                  skip=7, n_max = 10, trim_ws = TRUE,
                  sheet = "T1b solutions (local)", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::filter(
    grepl("uptake|warming|acidification|sea level|readiness|Affordability", Criteria)) %>%
  mutate_each(funs(substr(., 1, 1)), 2:10) %>%
  mutate_each(funs(as.integer), 2:10)

dat$Criteria[dat$Criteria == "Effectiveness to increase net carbon uptake"] <-  "Increase carbon uptake"
dat$Criteria[dat$Criteria == "Effectiveness to moderate warming"] <-  "Moderate warming"
dat$Criteria[dat$Criteria == "Effectiveness to moderate acidification (upper ocean/global)"] <-  "Moderate acidification"
dat$Criteria[dat$Criteria == "Effectiveness to moderate relative sea level rise"] <-  "Moderate relative sea level rise"
dat$Criteria[dat$Criteria == "Time commitment"] <-  "Time commitment"
dat$Criteria[dat$Criteria == "Technological readiness"] <-  "Readiness"
dat$Criteria[dat$Criteria == "Lead time until effective"] <-  "Lead\ntime"

# long form
dat_long <- gather(data = dat, key = Solution, value = score, 2:10) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))
levels(dat_long$Criteria) <- rev(levels(dat_long$Criteria))

# Plot t1b #####
fig_t1b <- ggplot(data = dat_long, 
                 aes(x=Solution, 
                     y=Criteria, fill=score)) +
  labs(x = NULL, y = NULL, title = NULL) +
  geom_tile(color="black", size=0.1) +
  scale_fill_gradient(name = NULL,
                      low = "white", high = "dodgerblue3",
                      space = "Lab", na.value = "gray90", guide = "legend",
                      labels = c("Nil", "Very low", "Low", "Moderate",
                                   "High", "Very high")) +
  scale_x_discrete(position = "top") +
  coord_equal() +
  guides(fill = guide_legend(reverse = TRUE)) +
  Mytheme(size_labs = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0))
fig_t1b
ggsave(filename = "../figs/fig_t1b.pdf", plot = fig_t1b, width = 5, height = 5, units = "cm")
```

```{r Table 2, warning=FALSE, echo=FALSE, message= FALSE}
dat <- read_xlsx(path = file_name,
                  skip=7, n_max = 7, trim_ws = TRUE,
                  sheet = "T2 Sensitivity", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-c(`Assessment guidance`, Caveats, `Who?`)) %>%
  mutate_each(funs(substr(., 1, 1)), 2:4) %>%
  mutate_each(funs(as.integer), 2:4)

dat$System[dat$System == "Shellfish fisheries and aquaculture"] <-  "Shellfish fisheries and aquaculture"
colnames(dat) <- c("System", "Warming", "Acidification", "Sea level rise")
# long form
dat_long <- gather(data = dat, key = Driver, value = score, 2:4) %>%
  dplyr::mutate(Driver = factor(Driver, levels = unique(as.character(Driver)))) %>%
  dplyr::mutate(System = factor(System, levels = unique(as.character(System))))

# Plot t2 #####
fig_t2 <- ggplot(data = dat_long, 
                 aes(y=Driver, 
                     x=System, fill=score)) +
  labs(x = NULL, y = NULL, title = NULL) +
  geom_tile(color="white", size=0.1) +
  scale_fill_gradient(low = "white", high = "dodgerblue", 
                        space = "Lab", na.value = "gray90", guide = "legend",
                        labels = c("Very low", "Low", "Moderate", 
                                   "High", "Very high")) +
  scale_x_discrete(position = "top") +
# scale_fill_viridis(alpha = 1,
#                      option = "plasma",
#                      direction = -1,
#                      name = NULL, 
#                      discrete = TRUE,
#                      labels = c("Nil", "Very low", "Low", "Moderate", 
#                                 "High", "Very high", "Not applicable")) +
  #facet_wrap(~Category, ncol=3) +
  coord_equal() +
  guides(fill = guide_legend(reverse = TRUE)) +
  Mytheme(size_labs = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0))
fig_t2
ggsave(filename = "../figs/fig_t2.pdf", plot = fig_t2, width = 25, height = 25, units = "cm")
```

```{r Table 3, fig.width = 13, fig.height = 13, warning=FALSE, echo=FALSE, message= FALSE}
# First three effectivenesseses
dat1 <- read_xlsx(path = file_name,
                  skip=8, n_max = 75, trim_ws = TRUE,
                  sheet = "T3_Systems-Ocean", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::filter(grepl("Effectiveness to mimise impacts from", Criteria)) %>%
  mutate_each(funs(as.integer), 3:18)
colnames(dat1) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")
dat1$Criteria[dat1$Criteria == "Effectiveness to mimise impacts from warming (T1a or T1b with T2)"] <-  "OW"
dat1$Criteria[dat1$Criteria == "Effectiveness to mimise impacts from ocean acidification (T1a or T1b with T2)"] <-  "OA"
dat1$Criteria[dat1$Criteria == "Effectiveness to mimise impacts from sea level rise (T1a or T1b with T2)"] <-  "SLR"

# Next three rows (need to extract scores)
dat2 <- read_xlsx(file_name,
                  skip=8, n_max = 75, trim_ws = TRUE,
                  sheet = "T3_Systems-Ocean", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::filter(grepl("other drivers|co-benefits|Unintended consequences", Criteria)) %>%
  mutate_each(funs(substr(., 1, 1)), 3:18) %>%
  mutate_each(funs(as.integer), 3:18)
colnames(dat2) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")
dat2$Criteria[dat2$Criteria == "Effectiveness of solution to reduce impacts on an ecosystem by reducing other drivers (=previous effectiveness)"] <-  "Other\ndrivers"
dat2$Criteria[dat2$Criteria == "Importance of co-benefits on function and services of this habitat (=previous criterion)"] <-  "Co-benefits"
dat2$Criteria[dat2$Criteria == "Unintended consequences  (0 loss of benefits or negative impact, >0 some benefits remain, 5 all benefits remain)"] <-  "Lack of unintended\nconsequences"

# bind and long form
dat <- rbind(dat1, dat2)
dat_long <- gather(data = dat, key = Solution, value = score, 3:18) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))

# Plot panels = Systems ####
dat_long <- gather(data = dat, key = Solution, value = score, 3:18) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))
fig_t3_1 <- ggplot(data = dat_long, 
                 aes(y=Solution, 
                     x=Criteria, fill=score)) +
  labs(x = NULL, y = NULL, title = NULL) +
  geom_tile(color="white", size=0.1) +
  scale_fill_gradient(low = "white", high = "dodgerblue", 
                        space = "Lab", na.value = "gray90", guide = "legend",
                        labels = c("Nil", "Very low", "Low", "Moderate", 
                                   "High", "Very high")) +
  facet_wrap(~Category, ncol=3) +
  coord_fixed(ratio = 0.3) +
  guides(fill = guide_legend(reverse = TRUE)) +
  Mytheme(size_labs = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
fig_t3_1
ggsave(filename = "../figs/fig_t3_1.pdf", plot = fig_t3_1, width = 25, height = 25, units = "cm")

# Plot panels = Solutions ####
dat_long <- gather(data = dat, key = Solution, value = score, 3:18) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))
fig_t3 <- ggplot(data = dat_long, 
                 aes(y=Category, 
                     x=Criteria, fill=score)) +
  labs(x = NULL, y = NULL, title = NULL) +
  geom_tile(color="white", size=0.1) +
  scale_fill_gradient(low = "white", high = "dodgerblue", 
                        space = "Lab", na.value = "gray90", guide = "legend",
                        labels = c("Nil", "Very low", "Low", "Moderate", 
                                   "High", "Very high")) +
  facet_wrap(~Solution, ncol=2) +
  coord_fixed(ratio = 0.3) +
  guides(fill = guide_legend(reverse = TRUE)) +
  Mytheme(size_labs = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
fig_t3
ggsave(filename = "../figs/fig_t3.pdf", plot = fig_t3, width = 25, height = 25, units = "cm")
```

```{r Combine plots, warning=FALSE, echo=FALSE, message= FALSE}
g <- arrangeGrob(fig_t1a, fig_t1b, ncol=2)
ggsave("../figs/fig_t1.png", g,width = 20, units = "cm")

g <- arrangeGrob(fig_t1a, fig_t1b, fig_t2, fig_t3, ncol=1)
ggsave("../figs/fig_tables.pdf", g)
```