---
  title: "Figures Ocean Solutions paper"
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
  code_folding: hide
fig_caption: yes
toc: yes
toc_float: yes
pdf_document:
  toc: yes
---
  
  
```{r prep, echo=FALSE, message= FALSE}
rm(list = ls())
library(tidyverse)
library(readxl)
library(knitr)       # kable : prettier data.frame output
library(viridis)
library(gridExtra)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
file_name <- "../../../interim_documents/backups_google_docs/Ocean Solutions Tables_2017-05-14f.xlsx"
```

```{r prepare data table 1a, warning=FALSE, echo=FALSE, message= FALSE}
dat <- read_xlsx(path = file_name,
                  skip=7, n_max = 8, trim_ws = TRUE,
                  sheet = "T1a solutions (global)", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::rename(Others = `Other Methods (CO2 extraction and storage, other GHG, hybrid)`)

dat$Criteria[dat$Criteria == "Effectiveness to increase net carbon uptake"] <-  "Increase carbon\nuptake"
dat$Criteria[dat$Criteria == "Effectiveness to moderate acidification (upper ocean/global)"] <-  "Moderate acidification"
dat$Criteria[dat$Criteria == "Effectiveness to moderate sea level rise"] <-  "Moderate\nsea level rise"
dat$Criteria[dat$Criteria == "Time commitment"] <-  "Time\ncommitment"
dat$Criteria[dat$Criteria == "Technological readiness"] <-  "Technological\nreadiness"
dat$Criteria[dat$Criteria == "Lead time until effective"] <-  "Lead\ntime"

  mutate_each(funs(as.integer), 3:18)
colnames(dat1) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")

# Next three rows (need to extract scores)
dat2 <- read_xlsx(file_name,
                  skip=17, n_max = 75, trim_ws = TRUE,
                  sheet = "T3_Systems-Ocean", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::filter(grepl("other drivers|co-benefits|Unintended consequences", Criteria))
colnames(dat2) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")
dat2$Criteria[dat2$Criteria == "Effectiveness of solution to reduce impacts on an ecosystem by reducing other drivers (=previous effectiveness)"] <-  "Other\ndrivers"
dat2$Criteria[dat2$Criteria == "Importance of co-benefits on function and services of this habitat (=previous criterion)"] <-  "Co-benefits"
dat2$Criteria[dat2$Criteria == "Unintended consequences  (0 loss of benefits or negative impact, >0 some benefits remain, 5 all benefits remain)"] <-  "Unintended\nconsequences"

tidyr::separate(data = dat2, col = Renewables, into = c("A", "B"), sep = "/")
#  mutate_each(funs(substr(., 1, 1)), 3:18) %>%
  mutate_each(funs(as.integer), 3:18)
colnames(dat2) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")
dat2$Criteria[dat2$Criteria == "Effectiveness of solution to reduce impacts on an ecosystem by reducing other drivers (=previous effectiveness)"] <-  "Other\ndrivers"
dat2$Criteria[dat2$Criteria == "Importance of co-benefits on function and services of this habitat (=previous criterion)"] <-  "Co-benefits"
dat2$Criteria[dat2$Criteria == "Unintended consequences  (0 loss of benefits or negative impact, >0 some benefits remain, 5 all benefits remain)"] <-  "Unintended\nconsequences"

#  tidyr::separate(data = dat2, col = Renewables, into = c("A", "B"))

# bind and long form
dat <- rbind(dat1, dat2)
dat_long <- gather(data = dat, key = Solution, value = score, 3:18) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))
```

```{r prepare data table 3, warning=FALSE, echo=FALSE, message= FALSE}
# First three effectivenesseses
dat1 <- read_xlsx(path = file_name,
                  skip=17, n_max = 75, trim_ws = TRUE,
                  sheet = "T3_Systems-Ocean", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::filter(grepl("Effectiveness to mimise impacts from", Criteria)) %>%
  mutate_each(funs(as.integer), 3:18)
colnames(dat1) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")
dat1$Criteria[dat1$Criteria == "Effectiveness to mimise impacts from warming (T1a or T1b with T2)"] <-  "OW"
dat1$Criteria[dat1$Criteria == "Effectiveness to mimise impacts from ocean acidification (T1a or T1b with T2)"] <-  "OA"
dat1$Criteria[dat1$Criteria == "Effectiveness to mimise impacts from sea level rise (T1a or T1b with T2)"] <-  "SLR"

# Next three rows (need to extract scores)
dat2 <- read_xlsx(file_name,
                  skip=17, n_max = 75, trim_ws = TRUE,
                  sheet = "T3_Systems-Ocean", col_names = TRUE,
                  col_types = "text") %>%
  dplyr::select(-`Assessment guidance`) %>%
  dplyr::filter(grepl("other drivers|co-benefits|Unintended consequences", Criteria)) %>%
  mutate_each(funs(substr(., 1, 1)), 3:18) %>%
  mutate_each(funs(as.integer), 3:18)
colnames(dat2) <- c("Category", "Criteria", "Renewables", "Vegetation (g)", "Productivity",
                    "Alkalinity (g)","Others", "Cloud", "Albedo", "Alkalinity (l)",
                    "Vegetation (l)", "Pollutants", "Hydrology", "Overexploitation",
                    "Protection", "Invasion", "Evolution",
                    "Relocation & Restoration")
dat2$Criteria[dat2$Criteria == "Effectiveness of solution to reduce impacts on an ecosystem by reducing other drivers (=previous effectiveness)"] <-  "Other\ndrivers"
dat2$Criteria[dat2$Criteria == "Importance of co-benefits on function and services of this habitat (=previous criterion)"] <-  "Co-benefits"
dat2$Criteria[dat2$Criteria == "Unintended consequences  (0 loss of benefits or negative impact, >0 some benefits remain, 5 all benefits remain)"] <-  "Unintended\nconsequences"

# bind and long form
dat <- rbind(dat1, dat2)
dat_long <- gather(data = dat, key = Solution, value = score, 3:18) %>%
  dplyr::mutate(Solution = factor(Solution, levels = unique(as.character(Solution)))) %>%
  dplyr::mutate(Criteria = factor(Criteria, levels = unique(as.character(Criteria))))
```

```{r plot effectiveness table 3, echo=FALSE, message= FALSE}
fig_t3 <- ggplot(data = dat_long, 
                 aes(y=Solution, 
                     x=Criteria, fill=as.factor(score))) +
  labs(x = NULL, y = NULL, title = NULL) +
  geom_tile(color="white", size=0.1) +
  scale_fill_viridis(alpha = 1,
                     option = "plasma",
                     direction = -1,
                     name = NULL, 
                     discrete = TRUE,
                     labels = c("Nil", "Very low", "Low", "Moderate", 
                                "High", "Very high", "Not applicable")) +
  facet_wrap(~Category, ncol=3) +
  coord_fixed(ratio = 0.3) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(filename = "../figs/fig_t3.pdf", plot = fig_t3, width = 25, height = 25, units = "cm")
```

