---
title: "Displays Ocean Solutions paper"
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r prep, echo=FALSE, message= FALSE}
rm(list = ls())
suppressPackageStartupMessages(library(tidyverse))
library(viridis)
#devtools::install_github("ricardo-bion/ggradar", dependencies=TRUE)
#library(ggradar)
#library(scales)
#download.file("https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular Air-Light 3.46.45 PM.ttf", "/Library/Fonts/Circular Air-Light 3.46.45 PM.ttf", method="curl")
#extrafont::font_import(pattern = 'Circular', prompt=FALSE)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
dat <- read_tsv(file = "T1.tsv")
```
```{r effectiveness line plots, echo=FALSE, message= FALSE}
d <- dat %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )

effectiveness_sol <- ggplot(data=d) +
  geom_point(aes(x=Solution, y=Value, group=Process, color=Process, size = Confidence),
                 position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Solution, ymin = 0, ymax = Value, colour = Process), 
                   position = position_dodge(width = 0.5)) +
  coord_polar() +
  labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_sol
ggsave(filename = "effectiveness_sol.png", plot = effectiveness_sol, width = 18, height = 12, units = "cm")

# rename processes
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"

effectiveness_proc <- ggplot(data=d) +
  geom_point(aes(x=Process, y=Value, group=Solution, color=Solution, size = Confidence),
                 position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Process, ymin = 0, ymax = Value, colour = Solution), 
                   position = position_dodge(width = 0.5)) +
  geom_polygon(data = test, aes(x = Process, y = Value)) +
  coord_polar() +
    labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  theme(legend.position = "top",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_proc
ggsave(filename = "effectiveness_proc.png", plot = effectiveness_proc)

#test <- filter(dat, Process == "Controversiality")
  # ggplot(d) + 
  #     geom_point(aes(x=Process, y=Value, group=Solution, color=Solution, size = Confidence),
  #                position = position_dodge(width = 0.5)) +
  #   geom_polygon(dat=filter(d, Process=="Controversiality"), aes(x=Process, 
  #                    y=Value, group=Solution)) +
  #     coord_polar()

```
  
  
```{r effectiveness bar plots, echo=FALSE, message= FALSE}
d <- dat %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )
# rename processes
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"


# #### Effectiveness bar plot
# fig_effectiveness <- ggplot(data=d,
#                             aes(x=Process, y=Value, fill=Solution)) +
#   coord_flip() +
#   geom_bar(stat = "identity", position = "dodge") +
#   scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
#   labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
#   geom_text(aes(y = Confidence, label = Confidence)) +
#   facet_grid(. ~ Group) +
#   theme(legend.position = "right",
#         axis.text.x = element_text(hjust=1),
#         axis.text.y = element_blank(),
#         axis.ticks = element_blank()
#         )
# fig_effectiveness
# ggsave(filename = "fig_effectiveness.png", plot = fig_effectiveness)

#### Effectiveness per solution bar radial
effectiveness_sol_bar <- ggplot(data=d,
                            aes(x=Solution, y=Value, group=Process, fill=Process)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_sol_bar
ggsave(filename = "effectiveness_sol_bar.png", plot = effectiveness_sol_bar)

#### Effectiveness per process bar radial
effectiveness_proc_bar <- ggplot(data=d,
                            aes(x=Process, y=Value, group=Solution, fill=Solution)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_proc_bar
ggsave(filename = "effectiveness_sol_proc.png", plot = effectiveness_proc_bar)
```

```{r controversiality and technological feasibility, echo=FALSE, message= FALSE}
d <- dat %>%
#  dplyr::mutate(Effectiveness = as.numeric(Effectiveness)) %>%
  dplyr::filter(Process %in% c("Controversiality", "Technological feasibility"),
                !is.na(Value))

# rename processes
d[d$Process == "Technological feasibility",]$Process <- "Technological\nfeasibility"
# d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
# d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
# d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"


#### fig_controversiality_feasibility radial
controversiality_feasibility <- ggplot(data=d,
                            aes(x=Solution, y=Value, group=Process, fill=Process)) +
  coord_flip() + coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Controversiality and technological feasibility of ocean-based solutions", x="", y="",
       fill = "") +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
controversiality_feasibility
ggsave(filename = "controversiality_feasibility.png", 
       plot = controversiality_feasibility)
```
