---
title: "Displays Ocean Solutions paper"
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r prep, echo=FALSE, message= FALSE}
rm(list = ls())
suppressPackageStartupMessages(library(tidyverse))
library(viridis)
#devtools::install_github("ricardo-bion/ggradar", dependencies=TRUE)
#library(ggradar)
#library(scales)
#download.file("https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular Air-Light 3.46.45 PM.ttf", "/Library/Fonts/Circular Air-Light 3.46.45 PM.ttf", method="curl")
#extrafont::font_import(pattern = 'Circular', prompt=FALSE)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
dat_sol <- read_tsv(file = "solutions.tsv")
dat_sys <- read_tsv(file = "systems.tsv")
```
```{r effectiveness ocean line plots, echo=FALSE, message= FALSE, warning=FALSE}
d <- dat_sol %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Ocean-based") %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )

effectiveness_ocean_sol <- ggplot(data=d) +
  geom_point(aes(x=Solution, y=Value, group=Process, color=Process, size = Confidence),
                 position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Solution, ymin = 0, ymax = Value, colour = Process), 
                   position = position_dodge(width = 0.5)) +
  coord_polar() +
  labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_ocean_sol
ggsave(filename = "effectiveness_ocean_sol.png", plot = effectiveness_ocean_sol, width = 18, height = 12, units = "cm")

# rename processes
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"

effectiveness_ocean_proc <- ggplot(data=d) +
  geom_point(aes(x=Process, y=Value, group=Solution, color=Solution, size = Confidence),
                 position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Process, ymin = 0, ymax = Value, colour = Solution), 
                   position = position_dodge(width = 0.5)) +
  #geom_polygon(data = test, aes(x = Process, y = Value)) +
  coord_polar() +
    labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  theme(legend.position = "top",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_ocean_proc
ggsave(filename = "effectiveness_ocean_proc.png", plot = effectiveness_ocean_proc)

#test <- filter(dat_sol, Process == "Controversiality")
  # ggplot(d) + 
  #     geom_point(aes(x=Process, y=Value, group=Solution, color=Solution, size = Confidence),
  #                position = position_dodge(width = 0.5)) +
  #   geom_polygon(dat_sol=filter(d, Process=="Controversiality"), aes(x=Process, 
  #                    y=Value, group=Solution)) +
  #     coord_polar()

```
  
  
```{r effectiveness ocean bar plots, echo=FALSE, message= FALSE, warning=FALSE}
d <- dat_sol %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Ocean-based") %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )
# rename processes
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"

#### Effectiveness per solution bar radial
effectiveness_ocean_sol_bar <- ggplot(data=d,
                            aes(x=Solution, y=Value, group=Process, fill=Process)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_ocean_sol_bar
ggsave(filename = "effectiveness_ocean_sol_bar.png", plot = effectiveness_ocean_sol_bar)

#### Effectiveness per process bar radial
effectiveness_ocean_proc_bar <- ggplot(data=d,
                            aes(x=Process, y=Value, group=Solution, fill=Solution)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_ocean_proc_bar
ggsave(filename = "effectiveness_ocean_proc_bar.png", plot = effectiveness_ocean_proc_bar)
```

```{r controversiality and technological feasibility, echo=FALSE, message= FALSE, warning=FALSE}
d <- dat_sol %>%
  dplyr::filter(Base == "Ocean-based",
                Process %in% c("Controversiality", "Technological feasibility"),
                !is.na(Value))

# rename processes
d[d$Process == "Technological feasibility",]$Process <- "Technological\nfeasibility"
# d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
# d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
# d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"


#### fig_controversiality_feasibility radial
controversiality_feasibility <- ggplot(data=d,
                            aes(x=Solution, y=Value, group=Process, fill=Process)) +
  coord_flip() + coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Controversiality and technological feasibility of ocean-based solutions", x="", y="",
       fill = "") +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
controversiality_feasibility
ggsave(filename = "controversiality_feasibility.png", 
       plot = controversiality_feasibility)
```

```{r effectiveness non-ocean line plots, echo=FALSE, message= FALSE, warning=FALSE}
d <- dat_sol %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Non-ocean-based") %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate warming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate acidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate sea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase carbon uptake"

d[d$Solution == "Afforestation and reforestation",]$Solution <- "Afforestation\nreforestation"
d[d$Solution == "Direct air capture",]$Solution <- "Direct\nair capture"
d[d$Solution == "Enhanced weathering",]$Solution <- "Enhanced\nweathering"
d[d$Solution == "Other GHG",]$Solution <- "Other\nGHG"
d[d$Solution == "Other biological",]$Solution <- "Other\nbiological"
d[d$Solution == "Land albedo",]$Solution <- "Land\nalbedo"
d[d$Solution == "Soil storage",]$Solution <- "Soil\nstorage"

effectiveness_non_ocean_sol <- ggplot(data=d) +
  geom_point(aes(x=Solution, y=Value, group=Process, color=Process, size = Confidence),
                 position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Solution, ymin = 0, ymax = Value, colour = Process), 
                   position = position_dodge(width = 0.5)) +
  coord_polar() +
  labs(title = "Effectiveness of non-ocean-based solutions", x="", y="") +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_non_ocean_sol
ggsave(filename = "effectiveness_non_ocean_sol.png", plot = effectiveness_non_ocean_sol, width = 18, height = 12, units = "cm")

# rename processes
d <- dat_sol %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Non-ocean-based") %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"
d[d$Solution == "Afforestation and reforestation",]$Solution <- "Afforestation\nreforestation"
d[d$Solution == "Direct air capture",]$Solution <- "Direct\nair capture"
d[d$Solution == "Enhanced weathering",]$Solution <- "Enhanced\nweathering"
d[d$Solution == "Other GHG",]$Solution <- "Other\nGHG"
d[d$Solution == "Other biological",]$Solution <- "Other\nbiological"
d[d$Solution == "Land albedo",]$Solution <- "Land\nalbedo"
d[d$Solution == "Soil storage",]$Solution <- "Soil\nstorage"

effectiveness_non_ocean_proc <- ggplot(data=d) +
  geom_point(aes(x=Process, y=Value, group=Solution, color=Solution, size = Confidence),
                 position = position_dodge(width = 0.5)) +
  geom_linerange(aes(x = Process, ymin = 0, ymax = Value, colour = Solution), 
                   position = position_dodge(width = 0.5)) +
  #geom_polygon(data = test, aes(x = Process, y = Value)) +
  coord_polar() +
    labs(title = "Effectiveness of non-ocean-based solutions", x="", y="") +
  theme(legend.position = "top",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_non_ocean_proc
ggsave(filename = "effectiveness_non_ocean_proc.png", plot = effectiveness_non_ocean_proc)
```
  
  
```{r effectiveness non-ocean bar plots, echo=FALSE, message= FALSE}
d <- dat_sol %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Non-ocean-based") %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )
# rename processes
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate warming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate acidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate sea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase carbon uptake"
d[d$Solution == "Afforestation and reforestation",]$Solution <- "Afforestation\nreforestation"


#### Effectiveness non--ocean per solution bar radial
d[d$Solution == "Direct air capture",]$Solution <- "Direct\nair capture"
d[d$Solution == "Enhanced weathering",]$Solution <- "Enhanced\nweathering"
d[d$Solution == "Other GHG",]$Solution <- "Other\nGHG"
d[d$Solution == "Other biological",]$Solution <- "Other\nbiological"
d[d$Solution == "Land albedo",]$Solution <- "Land\nalbedo"
d[d$Solution == "Soil storage",]$Solution <- "Soil\nstorage"

effectiveness_non_ocean_sol_bar <- ggplot(data=d,
                            aes(x=Solution, y=Value, group=Process, fill=Process)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of non-ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.margin=unit(c(0, 0, 0, 0),"cm")
        )
effectiveness_non_ocean_sol_bar
ggsave(filename = "effectiveness_non_ocean_sol_bar.png", plot = effectiveness_non_ocean_sol_bar)

#### Effectiveness per process bar radial
d <- dat_sol %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Non-ocean-based") %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake"),
                !is.na(Value)
                )
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"

effectiveness_non_ocean_proc_bar <- ggplot(data=d,
                            aes(x=Process, y=Value, group=Solution, fill=Solution)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of non-ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_non_ocean_proc_bar
ggsave(filename = "effectiveness_non_ocean_proc_bar.png", plot = effectiveness_non_ocean_proc_bar)
```


```{r systems ocean bar plots, echo=FALSE, message= FALSE, warning=FALSE}
d <- dat_sys %>%
  dplyr::mutate(Value = as.numeric(Value)) %>%
  dplyr::filter(Base == "Ocean-based")
  # dplyr::filter(Process %in% c("Effectiveness to moderate warming",
  #                             "Effectiveness to moderate acidification (global)",
  #                             "Effectiveness to moderate sea level rise",
  #                             "Effectiveness to increase carbon uptake"),
  #               !is.na(Value)
  #              )
# rename processes


#### systems per solution bar radial
sol <- unique(d$System)
n_sol <- length(sol)
for (i in 1:n_sol) {
file_name <- paste("system_ocean_sol_bar", as.character(i), sep = "_")
fig <- ggplot(data = filter(d, System==sol[i]),
                            aes(x=Solution, y=Value, group=System, fill=Process)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Systems and ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
}
ggsave(filename = file_name, plot = fig)

#### Effectiveness per process bar radial
effectiveness_ocean_proc_bar <- ggplot(data=d,
                            aes(x=Process, y=Value, group=Solution, fill=Solution)) +
  coord_polar() +
  geom_bar(stat = "identity", position = position_dodge(width = 1)) +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions (with confidence levels)", x="", y="") +
  geom_text(aes(y = Value + 0.3, label = Confidence), position = position_dodge(width = 1)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
effectiveness_ocean_proc_bar
ggsave(filename = "effectiveness_ocean_proc_bar.png", plot = effectiveness_ocean_proc_bar)
```