---
title: "Displays Ocean Solutions paper"
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r prep, echo=FALSE, message= FALSE}
rm(list = ls())
suppressPackageStartupMessages(library(tidyverse))
library(viridis)
#devtools::install_github("ricardo-bion/ggradar", dependencies=TRUE)
#library(ggradar)
#library(scales)
#download.file("https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular Air-Light 3.46.45 PM.ttf", "/Library/Fonts/Circular Air-Light 3.46.45 PM.ttf", method="curl")
#extrafont::font_import(pattern = 'Circular', prompt=FALSE)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
dat <- read_tsv(file = "T1.tsv")
```

```{r Effectiveness, echo=FALSE, message= FALSE}
d <- dat %>%
  dplyr::mutate(Effectiveness = as.numeric(Effectiveness)) %>%
  dplyr::filter(Process %in% c("Effectiveness to moderate warming",
                              "Effectiveness to moderate acidification (global)",
                              "Effectiveness to moderate sea level rise",
                              "Effectiveness to increase carbon uptake")
                )
# rename processes
d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"

#### Effectiveness bar plot
fig_effectiveness <- ggplot(data=d,
                            aes(x=Process, y=Effectiveness, fill=Solution)) +
  coord_flip() +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  geom_text(aes(y = Confidence, label = Confidence)) +
  facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
fig_effectiveness_phys_chem
ggsave(filename = "fig_effectiveness.png", plot = fig_effectiveness)

#### Effectiveness radial
fig_effectiveness_phys_chem <- ggplot(data=d,
                            aes(x=Process, y=Effectiveness, fill=Solution)) +
  coord_flip() + coord_polar() +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  geom_text(aes(y = Confidence, label = Confidence)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
fig_effectiveness_phys_chem
ggsave(filename = "fig_effectiveness_phys_chem.png", plot = fig_effectiveness_phys_chem)
```

```{r controversiality, echo=FALSE, message= FALSE}
d <- dat %>%
#  dplyr::mutate(Effectiveness = as.numeric(Effectiveness)) %>%
  dplyr::filter(Process = "Controversiality")

# # rename processes
# d[d$Process == "Effectiveness to moderate warming",]$Process <- "Moderate\nwarming"
# d[d$Process == "Effectiveness to moderate acidification (global)", ]$Process <- "Moderate\nacidification"
# d[d$Process == "Effectiveness to moderate sea level rise", ]$Process <- "Moderate\nsea level rise"
# d[d$Process == "Effectiveness to increase carbon uptake", ]$Process <- "Increase\ncarbon uptake"

#### Bar plot
fig_controversiality <- ggplot(data=d,
                            aes(x=Process, y=Controversiality, fill=Solution)) +
  coord_flip() +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  geom_text(aes(y = Confidence, label = Confidence)) +
  facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
fig_controversiality
ggsave(filename = "fig_effectiveness.png", plot = fig_effectiveness)

#### Effectiveness radial
fig_effectiveness_phys_chem <- ggplot(data=d,
                            aes(x=Process, y=Effectiveness, fill=Solution)) +
  coord_flip() + coord_polar() +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_viridis(alpha = 0.8, discrete = TRUE, option = "C") +
  labs(title = "Effectiveness of ocean-based solutions", x="", y="") +
  geom_text(aes(y = Confidence, label = Confidence)) +
  #facet_grid(. ~ Group) +
  theme(legend.position = "right",
        axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()
        )
fig_effectiveness_phys_chem
ggsave(filename = "fig_effectiveness_phys_chem.png", plot = fig_effectiveness_phys_chem)
```