---
title: "Figures Ocean Solutions manuscript"
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
  code_folding: hide
fig_caption: yes
toc: yes
toc_float: yes
pdf_document:
  toc: yes
---
  
```{r prep, echo=FALSE, message= FALSE}
rm(list = ls())
#devtools::install_github("ricardo-bion/ggradar", dependencies=TRUE)
library(tidyverse)
library(ggradar)
library(scales)
library(readxl)
library(knitr)       # kable : prettier data.frame output
library(gridExtra)
library(RColorBrewer)
library(ggrepel)
library(grid)
library(gridExtra)
library(gtable)
library(viridis)
#library(extrafont)
Sys.setlocale("LC_ALL", "en_US.UTF-8")
#extrafont::font_import(pattern = 'Verdana', prompt=FALSE)

Sys.setenv(TZ='UTC') # on utilise UTC
dat_list <- list()
cols_blues <- colorRampPalette(brewer.pal(9,"Blues"))(6)
cols_reds <- colorRampPalette(brewer.pal(9,"Reds"))(6)
names(cols_blues) <- c("0", "1", "2", "3", "4", "5")
names(cols_reds) <- c("0", "1", "2", "3", "4", "5")

size_labs <- 6
face_font <- "plain"

Mytheme <- function(size_labs = 6, face_font="plain", ...) {
  theme_bw() +
  theme(axis.text.x = element_text(face=face_font, size=size_labs, color="black"),
        axis.title.x = element_text(face=face_font, size=size_labs, 
                                    margin=margin(0,0,0,0,"pt")),
        axis.text.y = element_text(face=face_font, color="black", size=size_labs),
        axis.title.y = element_text(face=face_font, size=size_labs),
        axis.ticks.x = element_line(size=0.1),
        axis.ticks.y = element_line(size=0.1),
        axis.ticks.length = unit(1.1, "mm"),
        panel.grid.major = element_blank(),
#        panel.grid.major = element_line(size = 0.25, color="black",
#                                        linetype="dotted"),
        #aspect.ratio = 1 / 1,
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "lines")
)
}
```

```{r test radar plot, echo=FALSE, message= FALSE}

# Read data
tmp <- read_csv(file= "../data/table_1a.csv")


d <- tmp %>%
  filter(Criteria != 'Cost effectiveness')
  
  
ggradar(d)


# d <- tmp %>%
#   #dplyr::mutate(Duration=factor(Duration, levels = c(1:5))) %>%
#   #dplyr::mutate(Governability=round(Governability, digits=0))%>%
#   filter(Criteria != 'Cost effectiveness') %>%
#   #gather(Criteria, value, -Solution) %>% 
#   #spread(Solution, value) %>%
#   #as.tibble()
#   ggradar()
```

